services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.dev
    ports:
      - "3050:3050"
    volumes:
      - ./apps/web/src:/app/src
      - ./apps/web/public:/app/public
      - ./apps/web/constants:/app/constants
      - ./apps/web/index.html:/app/index.html
      - ./apps/web/vite.config.js:/app/vite.config.js
      - ./apps/web/.env.development:/app/.env.development
    environment:
      - NODE_ENV=development
